//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_logs
    {
        public int id { get; set; }
        public System.DateTime log_datetime { get; set; }
        public string action { get; set; }
        public string table_name { get; set; }
        public string user_agent { get; set; }
        public string old_data { get; set; }
        public string new_data { get; set; }
    }
}
