//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_games_categories
    {
        public int id { get; set; }
        public int game_id { get; set; }
        public int category_id { get; set; }
    
        public virtual game_categories game_categories { get; set; }
        public virtual public_games public_games { get; set; }
    }
}
