//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class g4_6it23Entities : DbContext
    {
        public g4_6it23Entities()
            : base("name=g4_6it23Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_logs> admin_logs { get; set; }
        public virtual DbSet<game_categories> game_categories { get; set; }
        public virtual DbSet<game_games_categories> game_games_categories { get; set; }
        public virtual DbSet<game_games_platforms> game_games_platforms { get; set; }
        public virtual DbSet<game_platforms> game_platforms { get; set; }
        public virtual DbSet<hrbac_permissions> hrbac_permissions { get; set; }
        public virtual DbSet<hrbac_roles> hrbac_roles { get; set; }
        public virtual DbSet<hrbac_roles_inherits> hrbac_roles_inherits { get; set; }
        public virtual DbSet<hrbac_roles_permissions> hrbac_roles_permissions { get; set; }
        public virtual DbSet<hrbac_users_roles> hrbac_users_roles { get; set; }
        public virtual DbSet<public_developers_games> public_developers_games { get; set; }
        public virtual DbSet<public_games> public_games { get; set; }
        public virtual DbSet<public_publishers_games> public_publishers_games { get; set; }
        public virtual DbSet<public_reviews> public_reviews { get; set; }
        public virtual DbSet<public_studios> public_studios { get; set; }
        public virtual DbSet<public_users> public_users { get; set; }
        public virtual DbSet<public_users_games> public_users_games { get; set; }
        public virtual DbSet<public_wishlists> public_wishlists { get; set; }
    }
}
