//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class public_developers_games
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int game_id { get; set; }
        public int studio_id { get; set; }
    
        public virtual public_games public_games { get; set; }
        public virtual public_studios public_studios { get; set; }
        public virtual public_users public_users { get; set; }
    }
}
